create a superuser token bool
lae/ansible-role-netbox pull request #128
Opened 2021-03-27 09:28 UTC by florianow

hey,
i create a new default for deploy a api token for the superuser. we needed this for our project and let you know about this :)
thanks!

2021-03-27 10:05 UTC, lae requested changes
Good style overall. Some additional things apart from the review comments:

- Please add documentation to the `README.adoc` for the new role variable explaining what it does.
- `create_token` might be a more appropriate name than 'token_enabled', since that's what's happening here.
- Preferably, the role variable should also be configured in `tests/group_vars` as well so that CI will test it.

2021-03-27 10:34 UTC, florianow commented on vars/main.yml
> +    print("changed")
Hi, i will do it in the evening, thanks for the quick review

2021-03-27 15:30 UTC, florianow commented on molecule/default/molecule.yml
> +    name: centos8
true, that was I didn't do it on purpose

2021-03-27 16:33 UTC, florianow commented
in our Environment we deploy the netbox with your role and after it we discover all of our infrastructure (that´s the reason for the token). We already use LDAP too. I changed it to an bool trigger and an or condition. I hope that's also fine for you.

2021-05-20 11:00 UTC, fiskhest commented
This'd be a great addition! Could we get a new review @lae ?

2021-05-20 11:27 UTC, lae requested changes
sorry, missed the followup comment. New review with a question.

2021-05-21 09:37 UTC, lae commented on tasks/deploy_netbox.yml
> +        - (not netbox_ldap_enabled) or (netbox_superuser_enabled)
I note that @florianow reacted, too, so let's go ahead and do this.

Let me know when you've pushed your revisions as a comment - I should see it on Discord if I'm not busy.

2021-05-21 14:22 UTC, florianow commented on tasks/deploy_netbox.yml
> +        - (not netbox_ldap_enabled) or (netbox_superuser_enabled)
Hey Guys, I'am not really sure about what i can do now because that's the first time I pull request in a Public Role like yours. What you wrote is fine for me. I already removed line 131 in my fork.

2021-05-21 15:58 UTC, lae commented on tasks/deploy_netbox.yml
> +        - (not netbox_ldap_enabled) or (netbox_superuser_enabled)
@florianow No worries. I just meant to leave a comment here after you were done making changes (because notifications are not sent when you make changes, so I wouldn't easily know if you made changes, but they are when you leave a comment).

2021-05-21 15:59 UTC, lae commented on .cache/roles/Musee Ullah.netbox
> +../..
@florianow This file still needs to be removed. (I'm also a bit curious how my name got here instead of "lae", but that's not very important)

2021-05-21 16:26 UTC, florianow commented on .cache/roles/Musee Ullah.netbox
> +../..
done :)

2021-05-22 04:23 UTC, merged

2021-05-22 04:47 UTC, lae commented
Changes merged, but squashed into one commit due to the noisy commit history.

This may pose an issue when trying to pull changes to your fork as you were working directly on your main branch (master) because the histories are different. There are various ways of dealing with this, but the easiest might just be deleting your fork and making a new fork. To avoid this in the future, consider creating a new temporary branch (we tend to call them "feature branches" or something similar, but they're technically all the same), making changes to that branch and then creating a PR off of that branch.

2021-05-22 06:56 UTC, florianow commented
HI, Thanks for the Information. I will do it like this in the future.