Netbox 3.0
lae/ansible-role-netbox pull request #141
Opened 2022-03-23 08:17 UTC by smutel

Fix #132 

Add tasks to support installation of Netbox 3.0:
* Use latest pip/setuptools in virtualenv => create first the virtualenv with latest pip/setuptools before installing other dependencies
* Change permissions on netbox home => when installing pip libraries the `{{ netbox_home }}/.cache` will be used so `{{ netbox_home }}` need to be owned by netbox user
* Update for Netbox **3.0** => some tasks has been marked only for netbox <= 3.0 / include https://github.com/lae/ansible-role-netbox/pull/139
* Setup housekeeping (https://github.com/lae/ansible-role-netbox/pull/134)

Some ideas/information were retrieved from:
* https://github.com/lae/ansible-role-netbox/pull/136
* https://github.com/lae/ansible-role-netbox/issues/132

2022-03-23 17:44 UTC, lae requested changes
Hey @smutel, thanks for pitching in. The compatibility matrix is a good idea.

Could you take a look at my comments and fix them as needed? (ask me anything if you need to)

2022-03-23 17:44 UTC, lae commented on tasks/deploy_netbox.yml
> +- name: Daily Housekeeping Cron Job
Just a nitpick on my part but can you add an action word here? e.g. `Schedule daily housekeeping cronjob`

2022-03-23 17:44 UTC, lae commented on tasks/deploy_netbox.yml
> +  when: netbox_stable and netbox_stable_version is version('3.0.0', '>=')
This should also apply to git-based installations. Can you find the commit hash in NetBox and update this as needed?

Your changes for this should look similar to this commit: https://github.com/lae/ansible-role-netbox/commit/8addd275253d50792db98309b146896d4ea717bd

2022-03-24 09:06 UTC, smutel commented on vars/main.yml
> +debian_compat_matrix:
Sure. Done in last push.

2022-03-24 09:12 UTC, smutel commented on tasks/main.yml
> +      NetBox item.netbox_version_min requires Python item.python_needed.
Sure. Done in last push.

2022-03-24 09:21 UTC, smutel commented on tasks/main.yml
> -    - netbox_stable and netbox_stable_version is version('2.8.0', '>=') or netbox_git
I removed the split.

2022-03-24 09:23 UTC, smutel commented on tasks/deploy_netbox.yml
> +- name: Daily Housekeeping Cron Job
Done

2022-03-24 09:26 UTC, smutel commented on tasks/deploy_netbox.yml
> +    virtualenv_command: "{{ netbox_python_binary }} -m venv"
Already done, no ?

2022-03-24 09:35 UTC, smutel commented on tasks/deploy_netbox.yml
> +  when: netbox_stable and netbox_stable_version is version('3.0.0', '>=')
Do you think it's commit `b10635a9b` for housekeeping ?

2022-03-24 09:38 UTC, smutel commented on tasks/deploy_netbox.yml
> +      when: netbox_stable and netbox_stable_version is version('3.0.0', '<')
The commit should be near this issue https://github.com/netbox-community/netbox/issues/6639. What commit id I should take ?

2022-03-24 13:21 UTC, smutel commented on tasks/deploy_netbox.yml
> +    virtualenv_command: "{{ netbox_python_binary }} -m venv"
Done in last push.

2022-03-24 20:34 UTC, lae commented on tasks/deploy_netbox.yml
> +  when: netbox_stable and netbox_stable_version is version('3.0.0', '>=')
doing a quick search, this seems to be the issue: https://github.com/netbox-community/netbox/issues/6590
and the commit: https://github.com/netbox-community/netbox/commit/d87ec82fe34d92a84ee6f2a97ba0a87a53eed015

2022-03-24 20:36 UTC, lae commented on tasks/deploy_netbox.yml
> +      when: netbox_stable and netbox_stable_version is version('3.0.0', '<')
PR: https://github.com/netbox-community/netbox/pull/6716

relevant merge commit: https://github.com/netbox-community/netbox/commit/028c876bcafbaede2731f191512bbebe3f1b6a9e

2022-03-24 20:39 UTC, lae commented on tasks/deploy_netbox.yml
> +- name: Daily Housekeeping Cron Job
Oh sorry, I meant that change only for the Ansible task, because tasks are actions. The cronjob name should stay the same (the cronjob name is a description of the cronjob that'll be added as a comment in the crontab,I believe).

2022-03-25 11:52 UTC, smutel commented on tasks/deploy_netbox.yml
> +- name: Daily Housekeeping Cron Job
Perhaps it's a better to solution to create a symlink as described in the [doc](https://github.com/netbox-community/netbox/pull/7863/files) ?

2022-03-25 11:53 UTC, smutel commented
Do you want I change the `netbox_stable_version` variable in this PR ?

2022-03-25 11:59 UTC, smutel commented on tasks/deploy_netbox.yml
> +  when: netbox_stable and netbox_stable_version is version('3.0.0', '>=')
Done in last push.

2022-03-25 12:12 UTC, smutel commented on tasks/deploy_netbox.yml
> +      when: netbox_stable and netbox_stable_version is version('3.0.0', '<')
Done in last push.

2022-03-25 13:54 UTC, lae commented
Yes, please do bump the `netbox_stable_version`.

2022-03-25 15:16 UTC, lae commented on tasks/deploy_netbox.yml
> +- name: Daily Housekeeping Cron Job
Not a good idea, the paths are fixed in that file: https://github.com/netbox-community/netbox/blob/develop/contrib/netbox-housekeeping.sh The job as you've written it seems fine as-is.

2022-03-25 15:32 UTC, lae commented on tasks/deploy_netbox.yml
> +- name: Daily Housekeeping Cron Job
Oh, that made me realise, the `user` parameter for this cronjob needs to be set to `{{ netbox_user }}` so that it runs the action as the netbox user.

I don't really have an issue specifying a file, but since this role manages the netbox user anyway, I think I would personally prefer all Netbox cronjobs to just be in the user's crontab file.

2022-03-25 17:35 UTC, lae commented on tasks/deploy_netbox.yml
> +- name: Daily Housekeeping Cron Job
@smutel I want to take back what I said about the crontab task earlier. I thought the crontab module would be modifying a file inside one of the `/etc/cron.*` directories, but I guess it's in `/var/spool/cron/crontabs` huh? So...I think I'm of the opinion of just using `/etc/cron.d/netbox` so that it easy to find.

I guess by default the role variable can be set to that, but I'm not sure whether it's really valuable enough to make this configurable.

2022-03-25 19:36 UTC, smutel commented on tasks/deploy_netbox.yml
> +- name: Daily Housekeeping Cron Job
`/etc/cron.d/netbox` is fine. I will remove the option to avoid the confusion. Have a nice week end.

2022-03-28 07:16 UTC, smutel commented on tasks/deploy_netbox.yml
> +- name: Daily Housekeeping Cron Job
Done.

2022-03-29 03:57 UTC, lae approved these changes
Added a couple changes myself after testing the role.

2022-03-29 03:59 UTC, merged