generate offline documentation during deployment
lae/ansible-role-netbox pull request #142
Opened 2022-03-25 17:30 UTC by karolyczovek

2022-03-25 18:53 UTC, lae requested changes

2022-03-25 18:53 UTC, lae commented on tasks/deploy_netbox.yml
> +          or netbox_git and _netbox_git_contains_trace_paths.rc == 0
`_netbox_git_contains_trace_paths.rc` refers to a specific git commit where the `trace_paths` command was introduced.

Please see commit 8addd275253d50792db98309b146896d4ea717bd for how this works. We basically identify the commit X feature was introduced, and version gate it via that commit. Can you update this to refer to the relevant commit in upstream (it should probably be a merge commit from the relevant PR)?

2022-03-28 09:41 UTC, karolyczovek commented on tasks/deploy_netbox.yml
> +          or netbox_git and _netbox_git_contains_trace_paths.rc == 0
Hmm.. even cable trace is not needed, will update PR in a minute

2022-03-28 09:45 UTC, karolyczovek commented on tasks/deploy_netbox.yml
> +          or netbox_git and _netbox_git_contains_trace_paths.rc == 0
should be fine now, generate docs if >3.1.0 or git

2022-03-29 04:09 UTC, lae commented on tasks/deploy_netbox.yml
> +          or netbox_git and _netbox_git_contains_trace_paths.rc == 0
People using `netbox_git` are not guaranteed to be on top of Netbox' development branch (they could be using their own fork). It still needs to be version gated via the relevant commit.

2022-03-29 12:38 UTC, karolyczovek commented on tasks/deploy_netbox.yml
> +          or netbox_git and _netbox_git_contains_trace_paths.rc == 0
ok, will try to lookup which comit introduced the local doc generation in netbox upstream

2022-03-29 12:39 UTC, karolyczovek commented on tasks/deploy_netbox.yml
> +          or netbox_git and _netbox_git_contains_trace_paths.rc == 0
7058d6ca5ae2901383874bcea5fedad31e165dca will be our friend

2022-03-29 12:53 UTC, karolyczovek commented on tasks/deploy_netbox.yml
> +          or netbox_git and _netbox_git_contains_trace_paths.rc == 0
changes implemeted

2022-03-29 19:25 UTC, lae approved these changes
LGTM, but I want to double check on one thing. The last commit changes the version gate from 3.1.0 to 2.12.0. It looks like the mkdocs commit was added to 3.0.0, so shouldn't it be set to that? (and 2.12.0 doesn't look like it exists) What's the reasoning behind that?

2022-03-30 04:56 UTC, karolyczovek commented
> LGTM, but I want to double check on one thing. The last commit changes the version gate from 3.1.0 to 2.12.0. > It looks like the mkdocs commit was added to 3.0.0, so shouldn't it be set to that? (and 2.12.0 doesn't look like >it exists) What's the reasoning behind that?

Might be i interpret wrong, https://github.com/netbox-community/netbox/issues/6328 mentions docs generation as 2.11 feature - this was the reasoning behind.

2022-03-30 05:18 UTC, lae commented
Nah, the version specified in that issue is just what the current version of Netbox was when that person opened a feature request. If you look at the commit, https://github.com/netbox-community/netbox/commit/7058d6ca5ae2901383874bcea5fedad31e165dca, it'll show you what tags it is under and the earliest seems to be 3.0-beta1. Anyway, merging this, thanks.

2022-03-30 05:22 UTC, merged