Allow optional install of uwsgi into Netbox venv
lae/ansible-role-netbox pull request #155
Opened 2023-01-12 00:06 UTC by tyler-8

Fixes #144 

Also added a new version constraint for NetBox v3.2 requiring Python 3.8

2023-01-18 08:32 UTC, lae requested changes

2023-01-18 08:32 UTC, lae commented on tasks/main.yml
> +- name: Install uWSGI via pip (inside venv, new behavior)
I'm not sure this task needs to be duplicated. Unless  `omit` doesn't work in the `virtualenv` parameter?

i.e. `virtualenv: "{{ netbox_uwsgi_in_venv | ternary(netbox_virtualenv_path, omit) }}"` (going off on memory, double check this syntax)

2023-01-18 08:32 UTC, lae commented on README.adoc
> +version used to created the virtual environment (normal/legacy behavior).
update phrasing here since it's a bit confusing to me

"...will be installed system-wide, into the library path of the python version used to..."

2023-02-09 08:35 UTC, p-rintz commented on tasks/main.yml
> +- name: Install uWSGI via pip (inside venv, new behavior)
I have tested the following 
`    virtualenv: "{{ omit if not netbox_uwsgi_in_venv else netbox_virtualenv_path }}"`
to work.

2023-10-06 11:44 UTC, lae approved these changes

2023-10-06 11:45 UTC, merged