Add `netbox_database_maintenance` variable
lae/ansible-role-netbox pull request #158
Opened 2023-01-29 13:58 UTC by MonsterDruide1

Some use cases might not be able to access the default `postgres` database. To make sure that this playbook also works in these scenarios, `maintenance_db` should be changed by using variables, passed from outside of the role.

The default should still remain on `postgres`:
https://docs.ansible.com/ansible/latest/collections/community/postgresql/postgresql_db_module.html

2023-01-29 14:39 UTC, lae commented on tasks/main.yml
> +    maintenance_db: "{{ netbox_database_maintenance }}"
Is this the only place that needs to reference it?

2023-01-29 15:00 UTC, MonsterDruide1 commented on tasks/main.yml
> +    maintenance_db: "{{ netbox_database_maintenance }}"
With this setup, it works for us locally... it might be useful to add to the socket connection method above as well, give me a minute to push that change as well.

2023-01-29 15:02 UTC, lae commented on tasks/main.yml
> +    maintenance_db: "{{ netbox_database_maintenance }}"
`templates/configuration.py.j2` also references database connection information, but if it's working for you without an edit there then I guess it's probably fine....

2023-01-29 15:02 UTC, MonsterDruide1 commented on tasks/main.yml
> +    maintenance_db: "{{ netbox_database_maintenance }}"
Done. Can't test it though, so ... careful with the change higher in the file.

2023-01-29 15:04 UTC, lae commented on tasks/main.yml
> +    maintenance_db: "{{ netbox_database_maintenance }}"
If you have Vagrant, you can actually test using vagrant. Otherwise I guess I'll try to test it, but I think it's probably fine in the first place if it's a default.

2023-01-29 15:08 UTC, lae approved these changes

2023-01-29 15:09 UTC, lae requested changes
Actually, almost forgot. Please update the `README.adoc` to include documentation for the new role variable and its usage.

2023-01-29 15:54 UTC, MonsterDruide1 commented
I have added it ... somewhere, not quite sure where/how you'd want me to document it.

2023-01-29 15:55 UTC, lae commented
There's a section that goes over the other database connection parameters. That would be where. Ctrl+F "netbox_database" should get you to it, I think, if you're not sure where.

2023-01-30 12:33 UTC, lae commented
@MonsterDruide1 I think you might have forgot to force push the documentation update, so pinging you just in case. (Also see my last comment if you need it.)

2023-02-02 07:08 UTC, MonsterDruide1 commented
Sorry, took some time with other stuff - does this documentation match your request?

2023-02-02 07:10 UTC, lae commented on README.adoc
> +netbox_database_maintenance: netbox_prod
Sorry, this should show what the default is set to (so `postgres` instead of `netbox_prod`)

2023-02-02 07:11 UTC, lae commented on README.adoc
> +	netbox_database_maintenance: netbox_prod
should be 4 spaces instead of a tab

2023-02-02 07:12 UTC, lae commented
Yeah, the documentation looks fine apart from the minor things I pointed out.

2023-02-02 11:16 UTC, lae approved these changes

2023-02-02 11:17 UTC, merged

2023-02-02 11:17 UTC, MonsterDruide1 commented on README.adoc
> +netbox_database_maintenance: netbox_prod
Alright, changed this one, but left the other one - that makes sense in the given example, as it uses a "known-to-be-existing-and-accessible" database table.

2023-02-02 11:20 UTC, lae commented on README.adoc
> +netbox_database_maintenance: netbox_prod
Yeah, the other one is actually using it in an example playbook to override it, so it's fine. It's just the Role Variables section where defaults are shown (to save having to look at the actual defaults files).