deploy local settings to shared and symlink
lae/ansible-role-netbox pull request #190
Opened 2024-11-26 22:17 UTC by sol1-matt

This PR configures local_settings.py.

This is required for the deployment of the branch plugin as this file must exist before the migrations are run if the plugin is enabled. You can't otherwise use this role if you want the branch plugin.

- The role now automatically tries to copy from `{{ playbook_dir }}/files/netbox/local_settings.py`, files/netbox as local_settings.py is a generic name that could be used by other plays or roles.
- Errors are ignored on the copy in place of testing if the files exists or a var being set
- The symlink creation tests for the existence of local_settings.py in the shared director. If a user add's local_settings.py to the shared directory manually the role will still use it.
- The role doesn't have a way to remove the local_settings.py from the shared directory, if the user wants to remove the local_settings.py they can remove it from shared.

2024-11-27 01:33 UTC, lae requested changes
Please see comments.

for own reference,
background on what the `local_settings.py` file is and why one would use it: https://github.com/netbox-community/netbox/issues/16127

2024-11-27 01:33 UTC, lae commented on tasks/deploy_netbox.yml
> +    src: "{{ playbook_dir }}/files/netbox/local_settings.py"
can you change this to be a role variable, e.g. `netbox_local_settings_file` (if you have a better name feel free to suggest it), and use the variable as the basis for whether or not this file exists and gets copied or not? e.g.

```yaml
- name: copy local_settings
  ansible.builtin.copy:
    src: "{{ netbox_local_settings_file }}"
    dest: "{{ netbox_shared_path }}/local_settings.py"
  when:
    - netbox_local_settings_file is defined
```

that way you don't need the additional `stat` task, nor do you need to use `ignore_errors`, and can use `{{ 'link' if netbox_local_settings_file is defined else 'absent' }}` instead in the symlink task.

we also don't want to just assume people know this feature exists, so having it in the role variables adds at the very least some visibility and configurability in case they prefer a different directory layout. that said, the role variable should also be added to the README with an explanation of its purpose afterwards.

2024-11-27 01:33 UTC, lae commented on tasks/deploy_netbox.yml
> +  copy:
Please use fully qualified module names for any new/modified tasks. (`ansible.builtin.copy`)

2024-11-27 01:33 UTC, lae commented on tasks/deploy_netbox.yml
> +    src: "{{ netbox_shared_path + '/local_settings.py' if netbox_local_settings_file_in_shared.stat.exists else omit }}"
This can be simplified afterwards too.

2024-11-27 01:33 UTC, lae commented on tasks/deploy_netbox.yml
> +  ignore_errors: yes
this task should also have a notify handler, not just the symlink task, because if the `local_settings.py` file changes on a later run the symlink doesn't get recreated and the notify handler from it won't execute either.

2024-11-27 22:54 UTC, sol1-matt commented on tasks/deploy_netbox.yml
> +    src: "{{ playbook_dir }}/files/netbox/local_settings.py"
The reason for the `ignore_errors` was if you have more than one netbox, say production and dev, and the local_settings.py needs to be different for each you can skip the role deployment of the different files and do that step as a `pre_task`.

The 2 ways I can see to get this aligned with what your suggesting and not lock it into a single file for all Netbox instances in a repo is
* keep `icinga_errors` and `stat` task and add `netbox_local_settings_enabled` boolean so you can use a `pre_task` to deploy the file to shared and the role will handle the symlinking
* add a `netbox_local_settings_file` string which is the filename that needs to be picked up and saved to `local_settings.py` then we don't need `icinga_errors: false` or the `stat` task but if you don't put the file in the right place it all fails (which seems fair enough)
```
netbox_local_settings_file: "local_settings_prod.py"
```

I think the second option is probably more sensible thinking about it more

2024-11-27 22:58 UTC, sol1-matt commented on tasks/deploy_netbox.yml
> +    src: "{{ playbook_dir }}/files/netbox/local_settings.py"
the second pattern would make more sense for #157 too, having consistency for end users on "how to deploy custom files that aren't templates" is nice

2024-11-27 22:59 UTC, lae commented on tasks/deploy_netbox.yml
> +    src: "{{ playbook_dir }}/files/netbox/local_settings.py"
the second option is exactly what I'm requesting. an admin should voluntarily enable the variable, and configure it differently per environment based on their own playbook layout/deployment pipelines (but we can suggest a sensible value for them to use, which is the one you already have in the PR).

2024-11-27 23:05 UTC, sol1-matt commented on tasks/deploy_netbox.yml
> +    src: "{{ playbook_dir }}/files/netbox/local_settings.py"
looking at ldap I should bring this in line with the vars for that except it is file not template
```
netbox_ldap_enabled: false
netbox_ldap_config_template: netbox_ldap_config.py.j2
```

2024-11-27 23:13 UTC, lae commented on tasks/deploy_netbox.yml
> +    src: "{{ playbook_dir }}/files/netbox/local_settings.py"
Hmm...
In the case of LDAP, there are other tasks specific to supporting LDAP asides from just copying the template over, such as injecting library dependencies into the list of venv packages, etc, so it simplifies things that part of the process.
I think for just a single file copy it'd be annoying to have two variables for it, unless there's additional configuration that needs to be done? The `is defined` test works well enough for a single task imo.

Definitely makes sense to use a boolean toggle for #157 though, since I guess you will need to modify `configuration.py.j2` to use it.

2024-11-27 23:24 UTC, sol1-matt commented
I've [committed changes](https://github.com/sol1-matt/ansible-role-netbox/commit/dcc474966e4a3097bfecf5ff9c2a2c3593a13c41) but still need to test them.

2024-11-28 04:54 UTC, sol1-matt commented on tasks/deploy_netbox.yml
> +    src: "{{ playbook_dir }}/files/netbox/local_settings.py"
I'll make this one a single var then and set the default to empty

2024-11-29 00:26 UTC, sol1-matt commented
@lae I've tested this now and updated the readme, the last commit for this is 282202a894e251eea9608a168b76d415a6afedf6. 
It is ready for merge.

2024-11-29 02:31 UTC, lae approved these changes

2024-11-29 02:36 UTC, lae commented
Just for future reference `is defined` is used to test if a variable is defined. Since we set an empty default it'll still error like below:

```
TASK [lae.netbox : Copy NetBox local_settings.py into shared (ignore if it doesn't exist)] ***************************************************************************************************
fatal: [10.17.0.122]: FAILED! => {"changed": false, "msg": "src (or content) is required"}
...ignoring

TASK [lae.netbox : Symlink/Remove NetBox local_settings.py file into/from the active NetBox release] *****************************************************************************************
fatal: [10.17.0.122]: FAILED! => {"changed": false, "msg": "src file does not exist, use \"force=yes\" if you really want to create the link: /srv/netbox/shared/local_settings.py", "path": "/srv/netbox/current/netbox/netbox/local_settings.py", "src": "/srv/netbox/shared/local_settings.py"}
```

We have a couple other role variables that only get used if they're defined, but just left commented out in the documentation and defaults file, so I applied that pattern here.

2024-11-29 02:37 UTC, merged

2024-11-29 02:39 UTC, lae commented
I just noticed: congrats on being the 100th PR on this project!